version: "3"
services:
#  mongo1:
#    hostname: dj1
#    image: mongo
#    container_name: "yc-db1"
#    environment:
#      - MONGO_INITDB_DATABASE=yc_db
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=123456
#    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#      - ./mongo-volume/db1:/data/db
#    expose:
#      - 27017
#    ports:
#      - "27017:27017"
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
#
#  mongo2:
#    hostname: dj2
#    image: mongo
#    container_name: "yc-db2"
#    environment:
#      - MONGO_INITDB_DATABASE=yc_db
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=123456
#    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
#      - ./mongo-volume/db2:/data/db
#    expose:
#      - 27017
#    ports:
#      - "28018:27017"
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  back_end_py:
    hostname: dj-py
    container_name: "yc-py"
    image: "yc-server:py"
    network_mode: host
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app
        gunicorn manager:app -c gunicorn.conf.py
#        gunicorn -w 4 -D --access-logfile ./log manager:app
#        gunicorn -w 4 -b 0.0.0.0:5000 -D --access-logfile ./log manager:app
#        python3 manager.py runserver

